name: denseCL-tinyImagenet
exp_num: 0
evl_frequent: 20
device: cuda
checkpoint: None
res_dir: './res'
dataset:
  name: tiny-imagenet
  download: False
  image_size: 32
  num_workers: 4
  data_dir: '/root/data/lyj/data/tiny-imagenet-200'
model:
  name: denseCL
  backbone: resnet50
  feature_dim: 128
  hyperparameter:
    K: 65536
    m: 0.999
    T: 0.2
    loss_lambda: 0.5
train:
  optimizer:
    name: sgd
    weight_decay: 0.0001
    momentum: 0.9
  warmup_lr: 0
  base_lr: 0.03
  final_lr: 0
  warmup_epochs: 4
  epochs: 200 # the sum epoch, influence the lr decay
  batch_size: 512
  knn_monitor: True
  knn_interval: 1
  knn_k: 200
eval: # linear evaluation, False will turn off automativ evaluation after training
  optimizer:
    name: sgd
    weight_decay: 0
    momentum: 0.9
  warmup_lr: 0
  base_lr: 3
  final_lr: 0
  batch_size: 512
  epochs: 100
  warmup_epochs: 0
logger:
  tensorboard: True
  matplotlib: True
debug: False
subset_size: 20